// src/gameData.js

export const ITEMS = {
  // ── Accessories (drop from purchases) ──
  twilly: {
    id: 'twilly',
    name: 'Twilly',
    description: 'A subtle touch.',
    score: 50,
    effect: 'socialBoost',
  },
  bracelet: {
    id: 'bracelet',
    name: 'Bracelet',
    description: 'Not your first purchase.',
    score: 100,
    effect: 'reputationBoost',
  },
  shoes: {
    id: 'shoes',
    name: 'Shoes',
    description: 'They notice everything.',
    score: 75,
    effect: 'moodRecovery',
  },
  kellyBelt: {
    id: 'kellyBelt',
    name: 'Kelly Belt',
    description: 'Closer.',
    score: 200,
    effect: 'dialogueUnlock',
  },
  scarfCarre: {
    id: 'scarfCarre',
    name: 'Carré H',
    description: 'Ninety centimetres of intention.',
    score: 125,
    effect: 'wardrobeDepth',
  },

  // ── Everyday bags (SA-offered, no quota required) ──
  evelyneTpm: {
    id: 'evelyneTpm',
    name: 'Evelyne TPM',
    description: 'Practical. She noticed.',
    score: 180,
    price: 2425,
    effect: 'socialBoost',
    everyday: true,
  },
  picotin18: {
    id: 'picotin18',
    name: 'Picotin 18',
    description: 'A basket. A statement.',
    score: 220,
    price: 3725,
    effect: 'socialBoost',
    everyday: true,
  },
  gardenParty: {
    id: 'gardenParty',
    name: 'Garden Party 36',
    description: 'She trusts you with canvas.',
    score: 200,
    price: 3975,
    effect: 'socialBoost',
    everyday: true,
  },
  bolide: {
    id: 'bolide',
    name: 'Bolide 1923 Mini',
    description: 'The original. Understated.',
    score: 320,
    price: 6900,
    effect: 'socialBoost',
    everyday: true,
  },
  roulis: {
    id: 'roulis',
    name: 'Roulis Mini',
    description: 'A quiet obsession.',
    score: 380,
    price: 9500,
    effect: 'socialBoost',
    everyday: true,
  },
  lindy26: {
    id: 'lindy26',
    name: 'Lindy 26',
    description: 'Effortless, yet deliberate.',
    score: 400,
    price: 9900,
    effect: 'socialBoost',
    everyday: true,
  },

  // ── Chapter 0 bags — accessible entry point ──
  constance24: {
    id: 'constance24',
    name: 'Constance 24',
    description: 'The beginning of something.',
    score: 350,
    price: 2000,
    effect: 'scoreMultiplier',
    chapter: 0,
    size: 'regular',
  },
  constanceMini: {
    id: 'constanceMini',
    name: 'Constance Mini',
    description: 'You weren\'t even looking for this.',
    score: 550,
    price: 2500,
    effect: 'scoreMultiplier',
    chapter: 0,
    size: 'mini', // Lucky Moment only
  },

  // ── Chapter 1 bags — requires relationship ──
  kelly28: {
    id: 'kelly28',
    name: 'Kelly 28',
    description: 'Structure. Restraint. Everything.',
    score: 600,
    price: 3000,
    effect: 'scoreMultiplier',
    chapter: 1,
    size: 'regular',
  },
  kelly25: {
    id: 'kelly25',
    name: 'Kelly 25',
    description: 'She made a call for this one.',
    score: 850,
    price: 3500,
    effect: 'scoreMultiplier',
    chapter: 1,
    size: 'mini', // Lucky Moment + high favor only
  },

  // ── Chapter 2 bags — the real game ──
  birkin30: {
    id: 'birkin30',
    name: 'Birkin 30',
    description: 'Oh.',
    score: 900,
    price: 4000,
    effect: 'scoreMultiplier',
    chapter: 2,
    size: 'regular',
  },
  birkin25: {
    id: 'birkin25',
    name: 'Birkin 25',
    description: 'There are no words.',
    score: 1400,
    price: 5000,
    effect: 'scoreMultiplier',
    chapter: 2,
    size: 'mini', // holy grail — requires everything
  },
};

export const NPC_DIALOGUE = {
  neutral: [
    'Good afternoon.',
    'Is there something I can help you with?',
    'We have some lovely pieces at the moment.',
    'Take your time. We\'re not going anywhere.',
    'Of course.',
  ],
  warm: [
    'How lovely to see you again.',
    'I was thinking of you just this morning.',
    'There\'s something I\'ve been setting aside.',
    'Your taste is really quite considered.',
    'I do enjoy our conversations.',
    'You know, not everyone notices that detail.',
    'I think we understand each other.',
  ],
  cold: [
    'That\'s not something we\'re able to help with today.',
    'We prefer to build these things over time.',
    'Interesting.',
    'Perhaps another visit would be more suitable.',
    'We do have other clients just now.',
    'I\'m afraid I\'m rather occupied.',
    'Mm.',
  ],
  afterAsk: [
    'That particular piece has a process.',
    'I wouldn\'t want to mislead you about timing.',
    'Some clients find patience is its own reward.',
    'We don\'t typically work that way.',
    'That piece requires a certain… context.',
    'Perhaps after you\'ve visited with us a bit more.',
    'I\'d hate to disappoint you.',
    'You\'re very… direct. That\'s one approach.',
  ],
  afterChat: [
    'How charming.',
    'You must know the Beaumont family.',
    'Yes, the autumn collection was exceptional.',
    'One develops an eye for these things.',
    'How refreshing to speak with someone who understands.',
    'I thought I recognized your sensibility.',
    'It\'s rare that one meets someone who truly appreciates the craft.',
    'Quite.',
  ],
  afterWait: [
    '(She glances at you briefly, then looks away.)',
    '(A slight nod. Something registered.)',
    '(She continues what she\'s doing. But differently.)',
    '(The briefest pause. Then back to the display case.)',
    '(She seems to appreciate that you\'re not rushing.)',
  ],
  saOffer: [
    'We\'ve just had something come in. I thought of you.',
    'There\'s a piece I\'ve been holding. Are you interested?',
    'I don\'t show this to everyone.',
    'I happened to set one aside. Purely by chance.',
    'You might appreciate this. We don\'t often have it available.',
  ],
  saOfferDecline: [
    'Of course. I understand completely.',
    'No pressure at all. It will find the right home.',
    'I appreciate your restraint. That says something.',
    'Very well. I\'ll keep you in mind.',
  ],
  afterFlip: [
    'We do prefer our pieces find permanent homes.',
    'I\'ll make a note of that.',
    'Interesting. I wasn\'t aware you\'d… divested.',
    'We tend to remember these things.',
  ],
  comboHint: [
    'You know, I\'ve been thinking — you might appreciate something we don\'t often show.',
    'There\'s a client who… actually, let me see what we have.',
    'I notice you have a certain approach. I respect that.',
    'Not everyone understands how this works. You seem to.',
    'I was going to mention — there\'s something that just came in.',
  ],
  highSuspicion: [
    'You seem very… eager.',
    'I notice you\'ve been asking about quite a few things.',
    'We appreciate enthusiasm, of course.',
    'Perhaps I can take your details and follow up.',
  ],
  returningClient: [
    'Oh. You\'re back.',
    'Well, this is a pleasant surprise.',
    'I remember you.',
    'I was hoping you\'d return.',
  ],
  loyalClient: [
    'You\'re back. Again.',
    'You know, not everyone has your patience.',
    'I\'ve come to expect you.',
    'There\'s something I\'ve been saving for someone like you.',
  ],
  postConstance: [
    'I heard the bag found a good home.',
    'She suits you, doesn\'t she?',
    'You understand the responsibility now.',
    'Welcome to a different kind of client.',
  ],
  postKelly: [
    'I\'ve been expecting you.',
    'You know what comes next. The question is whether you\'re ready.',
    'I think we both know what you\'re here for.',
    'Some clients never make it this far.',
  ],
  afterBuySmall: [
    'Subtle. I appreciate that.',
    'Small things reveal everything.',
    'Not everyone starts here. I noticed.',
    'A considered choice.',
    'It suits you. I can tell already.',
    'The details are always where it begins.',
  ],
  afterBuyMedium: [
    "Now we're speaking the same language.",
    'You understand commitment.',
    'I had a feeling about you.',
    "Yes. That's exactly right.",
    "That's more like it.",
    'This is how a relationship begins.',
  ],
  outfitChat: [
    "What you're describing — structured, but not stiff. That's very Constance.",
    "For something everyday, I'd think Evelyne. You seem like someone who moves.",
    "The Kelly reads formal, but she's surprisingly versatile. What's the occasion?",
    "If you're building a wardrobe around it — start with the scarf. Everything else follows.",
    'For travel? The Lindy. For arrival? The Kelly.',
    'You want people to notice, or you want them to wonder? Those are different bags.',
    'A Birkin is never casual. If you need casual, I have something else in mind.',
    'What you wear with it matters as much as the bag itself. What are we working with?',
    'The belt anchors everything. Once you have that, the bag becomes obvious.',
    'I always ask: is it for you, or is it for the room? The answer changes everything.',
    "There's a version of this that's very quiet. And a version that announces itself. Which are you?",
    "If you're wearing the scarf, the bag almost doesn't matter. Almost.",
  ],
  complimentReturn: [
    "I've been doing this long enough to trust my instincts.",
    "How kind. Most clients don't notice the display arrangement.",
    'I was wondering if anyone would say something about that.',
    "You're very perceptive. I appreciate that.",
    'It took us three weeks to find exactly the right piece for that corner.',
    'The craft deserves to be noticed. Thank you for seeing it.',
    "I don't often hear that. It means something, coming from you.",
  ],
  suspicionBuilding: [
    "You seem to have a very specific idea of what you're after.",
    "I want to make sure I understand what you're looking for, exactly.",
    'We like to get to know our clients a little first.',
    'Some clients find it helpful to come back another time.',
    "I'm just going to — excuse me one moment.",
    'We do move carefully here. I hope you understand.',
  ],
  itemSynergy: [
    "The scarf and the belt together — that's not an accident. You planned this.",
    'I notice you have the Twilly. The Kelly would complete that story.',
    'Someone who understands the belt already understands what comes next.',
    "The way you wear these things — it's consistent. That matters here.",
    "Your eye is getting sharper. I've been watching.",
    "You know, the bracelet reads differently with what you've chosen. It's working.",
    "I don't say this to everyone — but you're building something.",
    'That combination is very specific. Very you. I respect that.',
  ],
  chapterAware_ch1: [
    "You've been here before. I remember.",
    'Your Constance is settling in well, I hope?',
    "We've come a long way from our first conversation.",
    "You've earned a certain kind of conversation.",
    "I was hoping you'd come back.",
  ],
  chapterAware_ch2: [
    'This is a different kind of visit.',
    "I don't have many clients at this level.",
    "What you're looking for — it's not impossible. But it requires everything.",
    "We're not talking about the same world anymore.",
    "I hope you understand what's expected of someone in your position.",
  ],
};

export const EVERYDAY_BAGS = ['evelyneTpm', 'picotin18', 'gardenParty', 'bolide', 'roulis', 'lindy26'];

// Card types and their base weights (higher = more likely to appear).
// Weights are modified by game state in generateCards().
export const CARD_TEMPLATES = [
  {
    id: 'boutiqueVisit',
    type: 'boutiqueVisit',
    title: 'Boutique Visit',
    subtitle: 'The light is warm. The silence, deliberate.',
    baseWeight: 3,
    options: [
      { label: 'Buy Small Item — $500', action: 'buySmall', cost: 500 },
      { label: 'Buy Medium Item — $1,500', action: 'buyMedium', cost: 1500 },
      { label: 'Browse and Leave', action: 'leave', cost: 0 },
    ],
  },
  {
    id: 'talkToAssociate',
    type: 'talkToAssociate',
    title: 'The Associate',
    subtitle: 'She looks up from the display case.',
    baseWeight: 3,
    options: [
      { label: 'Ask About a Bag', action: 'ask', cost: 0 },
      { label: 'Chat Casually', action: 'chat', cost: 0 },
      { label: 'Compliment Her Taste', action: 'compliment', cost: 0 },
      { label: 'Discuss an Outfit', action: 'outfitChat', cost: 0 },
    ],
  },
  {
    id: 'wait',
    type: 'wait',
    title: 'Do Nothing',
    subtitle: 'Patience is its own currency.',
    baseWeight: 2,
    options: [
      { label: 'Wait This Turn', action: 'wait', cost: 0 },
    ],
  },
  {
    id: 'secondaryMarket',
    type: 'secondaryMarket',
    title: 'Secondary Market',
    subtitle: 'A discreet offer from someone with taste.',
    baseWeight: 1,
    options: [
      { label: 'Make the Arrangement (+$1,000)', action: 'flip', cost: 0 },
      { label: 'Decline', action: 'declineFlip', cost: 0 },
    ],
  },
  {
    id: 'luckyMoment',
    type: 'luckyMoment',
    title: 'A Quiet Opportunity',
    subtitle: 'Something rare has become... available.',
    baseWeight: 1, // increases with favor, decreases with suspicion
    options: [
      { label: 'Take the Risk', action: 'risk', cost: 0 },
      { label: 'Play It Safe', action: 'safe', cost: 0 },
    ],
  },
  {
    id: 'coldShoulder',
    type: 'coldShoulder',
    title: 'Cold Shoulder',
    subtitle: 'The temperature in the room has shifted.',
    baseWeight: 0, // only appears when suspicion is high
    options: [
      { label: 'Apologize', action: 'apologize', cost: 0 },
      { label: 'Leave Quietly', action: 'leaveQuietly', cost: 0 },
    ],
  },
];
